---
title: "Assignment"
author: "Bri Baker, Ian Brunjes, & Scout Leonard"
date: "5/11/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Consider the following model of forest growth (where forest size in measured in units of carbon (C))

dC/dt  = r*C  for forests where C is below a threshold canopy closure

dC/dt = g*(1- C/K) for forests where carbon is  at or above the threshold canopy closure

and K is a carrying capacity in units of carbon

The size of the forest (C), Canopy closure threshold and carrying capacity are all in units of kg carbon 

You could think of the canopy closure threshold as the size of the forest at which growth rates change from exponential to linear

You can think of r, as early exponential growth rate and g as the linear growth rate once canopy closure has been reached

Here's what you will do

1. Implement this model in R (as a differential equation) (Grading 25% - we will look for correct implementation but also good programming style - meaningful variable names, comments/documentation throughout,)

2. Run the model for 300 years (using the ODE solver)  starting with an initial forest size of 10 kgC, and using the following parameters

canopy closure threshold of 50 kgC 

 K = 250 kgC (carrying capacity) 

 r=  0.01 (exponential growth rate before before canopy closure)

 g = 2 kg/year (linear growth rate after canopy closure)

Graph the results. (15% - we look for an appropriate graphs and good visualization practice - labels, etc)

3. Run a Sobol sensitivity analysis that explores how the estimated maximum and mean forest size (e.g maximum and mean values of C over the 300 years) varies with the pre canopy closure growth rate (r) and post-canopy closure growth rate (g) and canopy closure threshold and carrying capacity(K)

Assume that parameters are all normally distributed with means as given above and standard deviation of 10% of mean value

Graph the results of the sensitivity analysis as a box plot of maximum forest size and a plot of the two Sobol indices (S and T). (25% - correct implementation of Sobol and graph We also look for good graphing style -labels etc)

In 2-3 sentences, discuss what the results of your simulation might mean for climate change impacts on forest growth (e.g think about what parameters climate change might influence ). (25% - we look for reasonable discussion that uses the results from your analysis and give extra points for discussions that offer particularly creative or insightful commentary)

Submit R markdown with model implementation, graphs and sensitivity analysis and R file with your model (Final 10% for well-organized, clearly documented R markdown)