---
title: 'EDS 230/ESM232: Assignment 7: Growth'
author: "Bri Baker, Ian Brunjes, Scout Leonard"
date: '`r format(Sys.time(), "%m/%d/%Y")`'
output: 
  pdf_document:
    toc: false
    number_sections: no
header-includes:
  - \setlength{\parindent}{1em}
  - \usepackage{float}
---

# Load Libraries

```{r load libraries, message = FALSE}
library(here)
library(sensitivity)
library(tidyverse)
library(pse)
```

# Source R Scripts

```{r source scripts}
source(here("R", "atmcond.R"))
```

# Implement Model

```{r}
atmcond
```


# Run Model

```{r}
# Results with baseline values
atmcond(h = 10, Vm = 250)
```

# Run a Sobel Sensitivity Analysis

```{r}
factors = c("h", "Kd", "K0", "Vm")
nsets = 100

q = c("qunif", "qnorm", "qnorm", "qnorm")
q.arg = list(
  list(
    min = 9.5,
    max = 10.5
  ),
  list(
    mean = 0.7,
    sd = 0.01 * 0.7
  ),
  list(
    mean = 0.1,
    sd = 0.01 * 0.1
  ),
  list(
    mean = 250,
    sd = 30
  )
)

sens_atmcond = LHS(NULL, factors, nsets, q, q.arg)
sens_pars = get.data(sens_atmcond)
head(sens_pars)

results = sens_pars %>% pmap(atmcond)

head(results)
resultsd = results %>% map_dfr(`[`,c("val"))

sens_atmcond = pse::tell(
  sens_atmcond,
  t(as.matrix(resultsd)),
  res.names = c("val")
)
```

## Plotting

```{r}
# now we use built in LHS functions to analyze parameter sensitivity
pse::plotscatter(sens_atmcond, col="blue", cex=5)

# we can also plot results in interesting ways

ggplot(resultsd, aes(minyield, maxyield))+geom_point()+labs(y="Max Yield (as anomoly)", "Min Yield (as anomoly")

# note that you don't see the ranges because of the scale (min yield anomoly much smaller than max) - here's a more informative way to graph
ggplot(resultsd)+
  geom_boxplot(aes(y = val))+labs(y="Yield (as anomoly)")

```


